services:
  - type: web
    name: myata-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: ВСТАВЬ_СЮДА_ТОКЕН_ИЗ_BOTFATHER
